### ISSUE TITLE
Congestion network 2.0: Gather nodes for routing

### ISSUE THREAD

**Issue by chmnata** [CityofToronto/bdit_congestion#53]
Minor arterial and above + traffic signals

**Comment by chmnata** [comment]
pulled traffic signal today again from gccview to get a more updated version before getting the nodes for traffic signals

**Comment by chmnata** [comment]
Since each px is tagged to a node_id in the layer from gccview, I checked to see if they match the centreline intersection version we have in the database.

The below code checked to see if the node_id (aka int_id) in the traffic signal layer is in the centreline_intersections. It returned 3 int_id that are not in the centreline_intersections, 2 at midblocks and 1 at a private access, I guess they updated the centreline_intersection layer to include these intersections...

I will be using the geometry of the traffic signal layer instead of the centreline layer for nearest neighbour with here nodes for these 3 + midblocks
```
-- returned 3 node_id that is not in centreline_intersection
-- node_id: 30119449, 30110360, 30121659
-- px: 2419, 2432, 2426

with t as (
	select node_id, px, geom 
	from gis.traffic_signal
	where node_id != 0 ) -- this is mostly to remove pxs that are at midblocks

select *
from t
left join gis.centreline_intersection on int_id = node_id
where int_id is null

**Comment by chmnata** [comment]
Selected the intersection + all traffic signals, but there are some traffic signals that are not on minor arterial and above. I'm gonna get rid of them but including the nodes that are within a certain buffer of centreline
![image](https://user-images.githubusercontent.com/46324452/168905495-712c693d-d373-4df0-866c-994133099f55.png)

**Comment by chmnata** [comment]
Forgot to add nodes for the end of road , e.g.
![image](https://user-images.githubusercontent.com/46324452/169076975-fa9a2761-2ae0-4d04-9630-18e03bbcf0cd.png)
gonna add a clause to include count(1) = 1

**Comment by chmnata** [comment]
Here nodes for routing are **mostly** clean meow (except highway, mainly lakeshore and gardiner madness), see below. 
![image](https://user-images.githubusercontent.com/46324452/169584082-39b4a584-5174-4a30-a142-7752eb73bd72.png)

The here nodes were first selected using a 50m buffer of selected centreline intersections (px + int), then it was cleaned on QGIS by manually removing extra ones. Using this seemingly more manual method because its easier to delete nodes manually then adding them. If we were to find the nearest neighbour using centreline int + px, we will have to add many nodes on streets that has medians. 
For example, on spadina. pink = here node, green = int/px. Nearest neighbour will only return 1 closest here node, and we will have then add the other direction later. 
![image](https://user-images.githubusercontent.com/46324452/169584814-092f3a90-fe84-4009-aaa2-4a57b8ffae29.png)

This will also be easier when we join here nodes and int/px layer together. We can find the closest int_id /px for each here nodes and assign information this way instead of the other way around (which will lead to more manual fixing later). 

While cleaning the layer, I realize there are a couple of cases where there are two very close selected intersections, e.g. below one has px and int_id as null and one has int_id but a null px. This is because our centreline layer is not as update as the traffic signal layer, so when I match px to the centreline intersection using int_id, some of them doesnt match. I will fix this by finding which int is very very close to another px with null int_id. 
Example: 
![image](https://user-images.githubusercontent.com/46324452/169586347-8d28971d-7cd0-40a2-a393-3dfec703fc05.png)

**Comment by radumas** [comment]
could the table of multiple :HERE: nodes for each px be useful for identifying special routing cases for da different directions?

**Comment by chmnata** [comment]
oh yesssss :meow_wow: , since they will be associate with 1 int_id, maybe we can find out the direction by the location of the nodes, like if the node is more to the north then its probably eastbound node and vice versa 🤔

**Comment by radumas** [comment]
:pig_ding:
I was alternatively thinking of doing a.... many to many routing for those to determine the direct path from intersection A to intersection B and vice-versa

**Comment by chmnata** [comment]
That would be so great if its all happening in a function :meow_ez:

**Comment by chmnata** [comment]
Was QCing and found pxs that were not including in the select intersections. This was because i excluded midblocks instead of including them ._. . Initially changed the sql to INCLUDE midblocks and exclude some outdated int_id, but then changed it to include all pxs with either no int_id or int_id that doesn't match with our current version of centreline with a left join instead. This will be easier to use later when we get more traffic signals in the future to include (and I don't have to manually check which is outdated and stuff). 

This added some extra px that I will have to add here_nodes for as well. new px = blue, original selected int + px = green, px not being selected (due to out of bound) = red
![image](https://user-images.githubusercontent.com/46324452/170525814-91647824-e5ea-4e0c-9c6d-91dc59d312ec.png)

**Comment by chmnata** [comment]
Welp this traffic signal (2438) is in the middle of a link_dir, apparently activated in 2016 so its not a new px that the 21_1 map version is not catching. 
![image](https://user-images.githubusercontent.com/46324452/171040045-cf5d2572-f98c-4939-9f30-6e0805474004.png)
![image](https://user-images.githubusercontent.com/46324452/171040627-c19a0992-12a1-4053-b50b-b91ee440c292.png)

**Comment by radumas** [comment]
That looks like a PXO. Those shouldn't be considered in the network

**Comment by radumas** [comment]
WTF
![image](https://user-images.githubusercontent.com/10623872/171041709-f226f1f6-7baf-4eca-ba39-43442bdb22f5.png)

**Comment by chmnata** [comment]
😢 
![image](https://user-images.githubusercontent.com/46324452/171041878-6703cfc3-d315-4587-bf9d-cde3e3e9bd59.png)

**Comment by radumas** [comment]
Might be worth checking in with Hao & Ihtesham if this is the kind of signal that would require signal timing/data at

**Comment by chmnata** [comment]
:meow_salute: lemme see if there are others, and then ask them all at once. Though if they want it, what should we do about it? Cut the link_dir in half? 🤔 or just say sorry we cant for these specific signals.

**Comment by radumas** [comment]
we could signal it to HERE...

**Comment by chmnata** [comment]
![image](https://user-images.githubusercontent.com/46324452/171047880-0125ed05-d4ca-46d1-93b0-eea81f417236.png)
the google street image is not up to date so I can't see if theres a signal. This was activated recently 2021-07-06, and it does say pushbutton actuated so most likely pxo

**Comment by radumas** [comment]
@qu-xiang is currently working on automating pulling in info on PXOs into the database

**Comment by chmnata** [comment]
PX 2600 - Rexdale and 200m east of Bergamot ave 
![image](https://user-images.githubusercontent.com/46324452/171213882-d7f0313e-cd10-4d76-84e7-120f54126e9f.png)
![image](https://user-images.githubusercontent.com/46324452/171214500-34f60625-b1ed-4ded-afaf-14887d55d28c.png)
I dont see ittttttttt

**Comment by radumas** [comment]
Parliament and Bloor should be considered one intersection I think.

**Comment by chmnata** [comment]
List of PX that are in the middle of link dir :
2593 - Parliament St & 130m WEST OF Bloor St E
2600 - Rexdale and 200m east of Bergamot ave
2552- EGLINTON AVE W 100m WEST OF PEAREN ST
2438- EGLINTON AVE W 45m WEST OF BRAEMAR AVE

**Comment by chmnata** [comment]
> Parliament and Bloor should be considered one intersection I think.

Yes parliament and bloor has one, and Parliament St & 130m west of Bloor St E also has one 
![image](https://user-images.githubusercontent.com/46324452/171233119-695c8113-4d0d-4397-ab46-4cf67a3b5cfb.png)

**Comment by chmnata** [comment]
PX 2379 - MARTIN GROVE RD 43m SOUTH OF RAMPART RD
![image](https://user-images.githubusercontent.com/46324452/171236752-fc054847-d30f-47c4-a5e6-084fb4f19de7.png)
![image](https://user-images.githubusercontent.com/46324452/171236796-90b84cbc-061e-439a-9a62-794da6055518.png)
![image](https://user-images.githubusercontent.com/46324452/171236838-ce4d6cec-56d5-476a-bb83-340ec8422318.png)
![image](https://user-images.githubusercontent.com/46324452/171236920-cdb7edeb-f42f-456e-8a5a-b3f820a63a53.png)

**Comment by radumas** [comment]
> > Parliament and Bloor should be considered one intersection I think.
> 
> Yes parliament and bloor has one, and Parliament St & 130m west of Bloor St E also has one ![image](https://user-images.githubusercontent.com/46324452/171233119-695c8113-4d0d-4397-ab46-4cf67a3b5cfb.png)

OHHHHHHHHHHHHHHHHHHHHHHHHHHHH. Yeah I remember this now.

**Comment by chmnata** [comment]
Cleaned all the nodes, ready for routing in `congestion.network_nodes`
![image](https://user-images.githubusercontent.com/46324452/172450526-c10120b9-d28d-47a6-b8b7-76646011653a.png)
